# Azure DevOps YAML Pipeline for Terraform Deployment
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.5.6' # Specify the Terraform version
  azureServiceConnection: '<Your-Service-Connection-Name>'
  terraformWorkingDirectory: '<Path-To-Terraform-Files>' # Example: 'terraform'

steps:
# Install Terraform
- task: UseTerraform@0
  inputs:
    terraformVersion: $(terraformVersion)

# # Initialize Terraform
# - task: TerraformCLI@0
#   inputs:
#     command: 'init'
#     workingDirectory: $(terraformWorkingDirectory)
#     backendServiceArm: $(azureServiceConnection)

# # Validate Terraform Configuration
# - task: TerraformCLI@0
#   inputs:
#     command: 'validate'
#     workingDirectory: $(terraformWorkingDirectory)

# # Plan Terraform Deployment
# - task: TerraformCLI@0
#   inputs:
#     command: 'plan'
#     workingDirectory: $(terraformWorkingDirectory)
#     backendServiceArm: $(azureServiceConnection)
#     additionalArguments: '-out=tfplan'

# # Apply Terraform Deployment
# - task: TerraformCLI@0
#   inputs:
#     command: 'apply'
#     workingDirectory: $(terraformWorkingDirectory)
#     backendServiceArm: $(azureServiceConnection)
#     additionalArguments: '-auto-approve tfplan'
