trigger:
- main

pool:
  name: 'my-agent-pool' 

# Azure DevOps YAML pipeline to install Azure CLI on Windows machine
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure_service_connect' # Replace with the name of your service connection
    scriptType: 'ps' # Use PowerShell script
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Authenticating to Azure using service connection..."
      az account show
