trigger:
- main

pool:
  name: 'my-agent-pool'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure_service_connect'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging into Azure subscription using Service Principal..."
      az account show
