trigger:
- main

pool:
  name: 'my-agent-pool'

# Azure DevOps YAML pipeline to install Azure CLI on Windows machine
steps:
- task: PowerShell@2
  displayName: Install Azure CLI
  inputs:
    targetType: inline
    script: |
      # Download and install Azure CLI
      Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi
      Start-Process msiexec.exe -ArgumentList '/i AzureCLI.msi /quiet /norestart' -Wait
      Write-Host "Azure CLI installed successfully."

