trigger:
- main

pool:
  name: 'my-agent-pool'

# Azure DevOps YAML pipeline to install Azure CLI on Windows machine
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest' # Specify the version you want, e.g., '1.5.0' or 'latest'

- script: |
    terraform --version
  displayName: 'Verify Terraform Installation'

