trigger:
- main

pool:
  name: 'my-agent-pool'

# Azure DevOps YAML pipeline to install Azure CLI on Windows machine
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Define the Terraform version to install
      $terraformVersion = "1.5.0" # Change to the desired version

      # Define the download URL for Terraform
      $url = "https://releases.hashicorp.com/terraform/$terraformVersion/terraform_${terraformVersion}_windows_amd64.zip"

      # Download Terraform zip file
      $outputPath = "$env:USERPROFILE\\terraform_${terraformVersion}.zip"
      Invoke-WebRequest -Uri $url -OutFile $outputPath

      # Extract the zip file
      $extractPath = "$env:USERPROFILE\\terraform"
      Expand-Archive -Path $outputPath -DestinationPath $extractPath -Force

      # Add Terraform to PATH
      $env:Path += ";$extractPath"

      # Verify Terraform installation
      terraform --version
  displayName: 'Install Terraform using PowerShell'

